### ISSUE TITLE
r10k puppetfile install clones git repos in a detached head state

### ISSUE THREAD

**Issue by natewalck** [puppetlabs/r10k#97]
When using 'r10k puppetfile install', it clones all the repos down in a detached head state. I would expect the modules to be checked out to the default branch and be able to  check out additional branches (if they exist).

**Comment by adrienthebo** [comment]
Unfortunately this issue is dramatically more complex than it may initially seem. Checking out a commit or tag is generally consistent as HEAD just points to a commit, but checking out a branch means initially creating a new branch and then later doing a pull on that branch. I started on an implementation of this but it got complex and messy very quickly.

In addition, supporting this use case directly conflicts with #47. Git is extremely bad at checking out only parts of a repository; sparse checkouts exist but do not serve to shift the desired subdirectory to the root of the repository. The only way to fake this out is to either do a `git subtree merge` which is deeply flawed for many reasons, or a `git filter-branch` to rewrite all of history, which is equally flawed for different reasons. In either case, these scenarios require drastically altering history which makes the repository worthless for further development. The best approach to this is to stop treating the checked out module as a Git repository and extract/copy the subdirectory into place.

In any case, all of the possible solutions horribly mangle the Git repository in question which makes them unsuitable for use further development. Trying to support actual branch checkouts per this issue and #47 together would require writing monstrous code that would look like it was copied from unspeakably terrible hieroglyphic murals sourced from R'lyeh.

While it would be convenient to use r10k to check out repositories for development purposes, unfortunately it's just not practical to do so; the cost of trying to make this work is enormously greater than asking users to `git clone` repositories. Git repository handling is going to move further away from having checkouts that are usable, which means that there won't be a current checkout at all, let along a checked out branch.

**Comment by c33s** [comment]
for development it would still be very very helpful. in fact i would even need the conflicting #47
if i mark a repo as "developent: true" it would be ok, to checkout the whole repo and then switch branch, additionally adding a path would be great, so i can control that whole repo modules reside in an own directory like modules_dev.

**Comment by c33s** [comment]
voting for reopen.

```
r10k puppetfile install --full-clones
```
just as a helper for iterating over all repos defined in the puppetfile and do a normal `git clone` or additional have a `:development => true` flag for each module
```
mod 'abstractit-puppet',
     :git => 'https://github.com/abstractitptyltd/abstractit-puppet.git',
     :install_path => 'modules/fork',
     :commit => 'c105b45fa7c3786163e8c491fe22de980c0534f8'
     :full_clone => true
```
doing a full git clone only for modules having the `:full_clone` flag and do a normal r10k processing for the rest.

**Comment by Raskil** [comment]
Hi,

I was looking for the same feature as c33s for the same reason (managing my code development environment). I worked around the problem. What I do is this:

I've setup a rake task which pulls down all module from my puppetfile with r10k puppetfile install
After that, I use the r10k Puppetfile parser to get all modules that were set to a :branch ref in the Puppetfile. For all of those modules, I do a checkout of that branch and a pull afterwards. Works like a charm. Here is my code for the checkout:
```ruby
pf = R10K::Puppetfile.new(puppetcontroldir, moduledir, puppetfile)
  pf.load!
  pf.modules.each { |x|
    if x.properties[:type] == :git
      args = x.instance_variable_get(:@args)
      if args.key?(:branch)
        Dir.chdir(x.path){
          puts %x{ "#{gitbin}" checkout #{x.desired_ref} }.strip
          puts %x{ "#{gitbin}" pull }.strip
        }
      end
    end
  }
```

**Comment by c33s** [comment]
@Raskil thanks for sharing, do you mind to add some more info how to add this to a normal r10k installation?

**Comment by Raskil** [comment]
@c33s 
well, that depends on how you setup looks like. It's not an actual part of my 'r10k installation' But this is how it works for me:

I've a git repository which hosts a vagrant VM for my puppet code dev purposes. In that git repo I have a rake task which can do two things: setup my dev environment (more on that later) and pull the puppet code with r10k.
The first task will just setup a filestructure for the puppet code to reside in and it will make sure that the code is shared with the VM.,so that I can directly edit code and test it on the VM. And it will checkout the control-repo in a defined place. This task is only needed once to setup the dev environment on a notebook or pc.

The second rake tasks does the actual r10k stuff. It looks like this:
```ruby
desc 'Pull down modules in Puppetfile'
task :pull do
  puts "Pulling down new modules in #{puppetfile} to #{moduledir}"
  unless system("r10k puppetfile install --puppetfile #{puppetfile} --moduledir #{moduledir}")
    abort 'Failed to build out Puppet module directory. Exiting...'
  end
  puts 'New modules successfully pulled down'
  puts 'Checking out branches.'
  pf = R10K::Puppetfile.new(puppetcontroldir, moduledir, puppetfile)
  pf.load!
  pf.modules.each { |x|
    if x.properties[:type] == :git
      args = x.instance_variable_get(:@args)
      if args.key?(:branch)
        Dir.chdir(x.path){
          puts %x{ "#{gitbin}" checkout #{x.desired_ref} }.strip
          puts %x{ "#{gitbin}" pull }.strip
        }
      end
    end
  }
end
```

I can now use the rake task via command line with "rake pull" or (which is my use case) from RubyMine.
The task will read the Puppetfile from my control-repo and pull all my modules. 
What my mentioned code does is it will make sure that repos that are mentioned in the Pupeptfile with the :branch option are not checked out in detached head but rather in that actual branch, so that I can start to work with them.

So when I want to develop modules or fixes for modules I put them into the Puppetfile with a :branch reference, trigger the rake task to actually pull all the modules and end up with the module I want to change/develop with a checkedout branch instead of a detached head.

**Comment by c33s** [comment]
and again crashing into this. the DX is just awful. building workarounds for something which really should be in the core.

@adrienthebo can't really belive that a regular noncached git clone put in an if branch be such a "monstrous code that would look like it was copied from unspeakably terrible hieroglyphic murals sourced from R'lyeh"

```
if ($flag==='--full-checkout') {
    exec('git clone ...');
} else {
   ...do what is currently be done...
}
```

if it is documented that `--full-checkout` conflicts with #47 than it simply does not matter but rebuilding the puppetfile parsing and handle the repo checkout by hand feels really wrong. can't be the code from @Raskil some kind of solution? only just integrated in r10k itself.

@Raskil sadly the code you provided is no drop in solutions (and i am no ruby coder to simply complement it in no time.

```
rake pull
rake aborted!
NameError: undefined local variable or method `puppetfile'
```
